<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-OB1OE1J" failures="0" tests="1" name="Default test(failed)" time="38.599" errors="0" timestamp="2021-07-23T07:58:42 IST">
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="38.56">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 36 more
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.CattleRegistration.RegisterBullCattle" name="registerBullCattle" time="0.0">
    <skipped/>
  </testcase> <!-- registerBullCattle -->
  <testcase classname="com.nitara.CattleRegistration.RegisterBullCattle" name="Registerwithmorethan25yeardsofage" time="0.0">
    <ignored/>
  </testcase> <!-- Registerwithmorethan25yeardsofage -->
  <testcase classname="com.nitara.CattleRegistration.RegisterBullCattle" name="Registerwithduplicatetagnumber" time="0.0">
    <ignored/>
  </testcase> <!-- Registerwithduplicatetagnumber -->
  <testcase classname="com.nitara.CattleRegistration.RegisterBullCattle" name="registerwithoutyearofbirth" time="0.0">
    <ignored/>
  </testcase> <!-- registerwithoutyearofbirth -->
  <testcase classname="com.nitara.CattleRegistration.RegisterBullCattle" name="Registerwithlessthan6monthsofage" time="0.0">
    <ignored/>
  </testcase> <!-- Registerwithlessthan6monthsofage -->
  <testcase classname="com.nitara.CattleRegistration.RegisterBullCattle" name="Registerwithduplicatecotagnumber" time="0.0">
    <ignored/>
  </testcase> <!-- Registerwithduplicatecotagnumber -->
  <testcase classname="com.nitara.CattleRegistration.RegisterBullCattle" name="registerwithemptytagnumbers" time="0.0">
    <ignored/>
  </testcase> <!-- registerwithemptytagnumbers -->
</testsuite> <!-- Default test(failed) -->
